/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LgmSingleAnswer {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
  }
  interface LgmSingleAnswerAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LgmSingleAnswer': Components.LgmSingleAnswer;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'lgm-single-answer': Components.LgmSingleAnswerAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLLgmSingleAnswerElement extends Components.LgmSingleAnswer, HTMLStencilElement {}
  var HTMLLgmSingleAnswerElement: {
    prototype: HTMLLgmSingleAnswerElement;
    new (): HTMLLgmSingleAnswerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'lgm-single-answer': HTMLLgmSingleAnswerElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'lgm-single-answer': HTMLLgmSingleAnswerElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
