/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface UmiakQuiz {
    'heading': string;
    'load': () => void;
    'question': string;
    'test': () => void;
  }
  interface UmiakQuizAttributes extends StencilHTMLAttributes {
    'heading'?: string;
    'question'?: string;
  }

  interface UmiakSingleAnswer {
    'alt_a': string;
    'alt_b': string;
    'alt_c': string;
    'alt_d': string;
    'handleOnAnswer': (event: Event) => void;
    'heading': string;
    'point_a': number;
    'point_b': number;
    'point_c': number;
    'point_d': number;
    'question': string;
  }
  interface UmiakSingleAnswerAttributes extends StencilHTMLAttributes {
    'alt_a'?: string;
    'alt_b'?: string;
    'alt_c'?: string;
    'alt_d'?: string;
    'heading'?: string;
    'point_a'?: number;
    'point_b'?: number;
    'point_c'?: number;
    'point_d'?: number;
    'question'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'UmiakQuiz': Components.UmiakQuiz;
    'UmiakSingleAnswer': Components.UmiakSingleAnswer;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'umiak-quiz': Components.UmiakQuizAttributes;
    'umiak-single-answer': Components.UmiakSingleAnswerAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLUmiakQuizElement extends Components.UmiakQuiz, HTMLStencilElement {}
  var HTMLUmiakQuizElement: {
    prototype: HTMLUmiakQuizElement;
    new (): HTMLUmiakQuizElement;
  };

  interface HTMLUmiakSingleAnswerElement extends Components.UmiakSingleAnswer, HTMLStencilElement {}
  var HTMLUmiakSingleAnswerElement: {
    prototype: HTMLUmiakSingleAnswerElement;
    new (): HTMLUmiakSingleAnswerElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'umiak-quiz': HTMLUmiakQuizElement
    'umiak-single-answer': HTMLUmiakSingleAnswerElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'umiak-quiz': HTMLUmiakQuizElement;
    'umiak-single-answer': HTMLUmiakSingleAnswerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
