/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface UmiakSingleAnswer {
    'first': string;
    'last': string;
  }
  interface UmiakSingleAnswerAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'UmiakSingleAnswer': Components.UmiakSingleAnswer;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'umiak-single-answer': Components.UmiakSingleAnswerAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLUmiakSingleAnswerElement extends Components.UmiakSingleAnswer, HTMLStencilElement {}
  var HTMLUmiakSingleAnswerElement: {
    prototype: HTMLUmiakSingleAnswerElement;
    new (): HTMLUmiakSingleAnswerElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'umiak-single-answer': HTMLUmiakSingleAnswerElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'umiak-single-answer': HTMLUmiakSingleAnswerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
